Repository Team-Oriddle/orridle-frontend, pull requests merged in 2024-02, with the labels that each got.

#25 chore: styled-components => tailwindcss, router.d.ts 추가
  package.json
  postcss.config.js
  src/components/test.vue
  src/global-styles.js
  src/main.ts
  src/router/router.d.ts
  src/style.css
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: ⚙️ chore

#26 Design/10 publishing login page
  README.md
  src/components/HelloWorld.vue
  src/pages/Auth/AuthPage.vue
  src/pages/Auth/api/index.ts
  src/pages/Auth/components/LoginForm.vue
  src/pages/Auth/components/SignupForm.vue
  src/pages/Auth/types/index.ts
  src/pages/Auth/utils/index.ts
  src/router/router.js
  src/style.css
  tailwind.config.js
  yarn.lock
Labels: ⚙️ chore, 📱 design

#28 Design/22 header 초안 제작, 전역 컨테이너 스타일 지정
  src/App.vue
  src/components/Header.vue
  src/components/HelloWorld.vue
  src/style.css
  tailwind.config.js
Labels: ⚙️ chore, 💫 feat, 📱 design

#33 Design/12 quiz room
  src/components/Header.vue
  src/components/QuizLayout.vue
  src/pages/quiz_room/QuizRoomPage.vue
  src/pages/quiz_room/components/ChatWindow.vue
  src/pages/quiz_room/components/ParticipantList.vue
  src/pages/quiz_room/components/QuizRoomInfo.vue
  src/pages/quiz_room/components/StartGameButton.vue
  src/pages/quiz_room/components/index.vue
  src/router/router.js
Labels: 📱 design

#35 Design/15 publishing quiz game page
  src/components/QuizLayout.vue
  src/pages/quiz_game/QuizGamePage.vue
  src/pages/quiz_game/components/ChatInput.vue
  src/pages/quiz_game/components/PlayerList.vue
  src/pages/quiz_game/components/QuestionInfo.vue
  src/pages/quiz_game/components/index.vue
  src/router/router.js
Labels: 💫 feat, 📱 design, ⚠️self-merged

#36 Design/16 publishing quiz attend
  README.md
  src/pages/quiz_attend/QuizAttendPage.vue
  src/pages/quiz_attend/data/mockData.ts
  src/router/router.js
Labels: 💫 feat, 📱 design

#37 feat: 퀴즈 결과 페이지 1차 퍼블리싱
  src/pages/quiz_result/QuizResultPage.vue
  src/pages/quiz_result/components/ResultHeader.vue
  src/pages/quiz_result/components/ResultStats.vue
  src/pages/quiz_result/components/TopStats.vue
  src/pages/quiz_result/components/index.vue
  src/pages/quiz_result/data/mockData.ts
  src/router/router.js
Labels: 💫 feat, 📱 design

#38 Design/11 main page
  src/pages/main/MainPage.vue
  src/pages/main/api/index.ts
  src/pages/main/components/QuizList.vue
  src/pages/main/components/QuizPreview.vue
  src/pages/main/components/SearchBar.vue
  src/pages/main/data/mockData.ts
  src/pages/main/types/index.ts
  src/pages/main/utils/index.ts
  src/router/router.js
Labels: 💫 feat, 📱 design

#41 fix : 누락된 라인 수정
  src/router/router.js
Labels: 🐛bug, ⚠️self-merged
